### ISSUE TITLE
0.15 Update?

### ISSUE THREAD

**Issue by abordoli** [Lockyy/More-Circuit-Symbols#3]
Really miss these symbols! Any chance that you can update the mod to 0.15?
Regards,
~B

**Comment by Lockyy** [comment]
An update for 0.15 is now up. I've included a few other changes to how the mod works including adding Available bots (since that's what the roboport's actually provide as a variable) and putting the bot related signals in as the default signals that roboport's provide.

**Comment by abordoli** [comment]
Thanks!
